// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T00
    {
        /// <summary>
        /// 選單代碼
        /// </summary>
        public string T0001 { get; set; }
        /// <summary>
        /// 選單名稱
        /// </summary>
        public string T0002 { get; set; }
        /// <summary>
        /// 使用者ID
        /// </summary>
        public string T0003 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T0004 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T0005 { get; set; }
        /// <summary>
        /// 刪除註記
        /// </summary>
        public string T0006 { get; set; }
    }
}