// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T01
    {
        /// <summary>
        /// 部位大類序號
        /// </summary>
        public string T0101 { get; set; }
        /// <summary>
        /// 部位大類代碼
        /// </summary>
        public string T0102 { get; set; }
        /// <summary>
        /// 部位大類名稱
        /// </summary>
        public string T0103 { get; set; }
        /// <summary>
        /// 失效日期
        /// </summary>
        public string T0104 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T0105 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T0106 { get; set; }
    }
}