// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T02
    {
        /// <summary>
        /// 部位中類代碼
        /// </summary>
        public string T0201 { get; set; }
        /// <summary>
        /// 部位中類名稱
        /// </summary>
        public string T0202 { get; set; }
        /// <summary>
        /// 失效日期
        /// </summary>
        public string T0203 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T0204 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T0205 { get; set; }
    }
}