// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T041
    {
        /// <summary>
        /// 物料料號
        /// </summary>
        public string T04101 { get; set; }
        /// <summary>
        /// 長度上限
        /// </summary>
        public decimal T04102 { get; set; }
        /// <summary>
        /// 長度單位Unit
        /// </summary>
        public string T04103 { get; set; }
        /// <summary>
        /// 備損係數
        /// </summary>
        public decimal T04104 { get; set; }
        /// <summary>
        /// 備損加量
        /// </summary>
        public decimal T04105 { get; set; }
        /// <summary>
        /// 備損單位Unit
        /// </summary>
        public string T04106 { get; set; }
        /// <summary>
        /// 效期(起)
        /// </summary>
        public string T04107 { get; set; }
        /// <summary>
        /// 效期(迄)
        /// </summary>
        public string T04108 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T04109 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T04110 { get; set; }
        /// <summary>
        /// 刪除註記
        /// </summary>
        public string T04111 { get; set; }
        /// <summary>
        /// 產品廠
        /// </summary>
        public string T04112 { get; set; }
    }
}