// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T042
    {
        /// <summary>
        /// 物料大中類
        /// </summary>
        public string T04201 { get; set; }
        /// <summary>
        /// 長度上限
        /// </summary>
        public decimal T04202 { get; set; }
        /// <summary>
        /// 長度單位Unit
        /// </summary>
        public string T04203 { get; set; }
        /// <summary>
        /// 備損係數
        /// </summary>
        public decimal T04204 { get; set; }
        /// <summary>
        /// 備損加量
        /// </summary>
        public decimal T04205 { get; set; }
        /// <summary>
        /// 備損單位Unit
        /// </summary>
        public string T04206 { get; set; }
        /// <summary>
        /// 效期(起)
        /// </summary>
        public string T04207 { get; set; }
        /// <summary>
        /// 效期(迄)
        /// </summary>
        public string T04208 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T04209 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T04210 { get; set; }
        /// <summary>
        /// 刪除註記
        /// </summary>
        public string T04211 { get; set; }
        /// <summary>
        /// 產品廠
        /// </summary>
        public string T04212 { get; set; }
    }
}