// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T05
    {
        /// <summary>
        /// 輔料簡稱代碼
        /// </summary>
        public string T0501 { get; set; }
        /// <summary>
        /// 輔料簡稱名稱
        /// </summary>
        public string T0502 { get; set; }
        /// <summary>
        /// 失效日期
        /// </summary>
        public string T0503 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T0504 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T0505 { get; set; }
    }
}