// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T06
    {
        /// <summary>
        /// 產品廠
        /// </summary>
        public string T0601 { get; set; }
        /// <summary>
        /// 製造廠
        /// </summary>
        public string T0602 { get; set; }
        /// <summary>
        /// 失效日期
        /// </summary>
        public string T0603 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T0604 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T0605 { get; set; }
    }
}