// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T07
    {
        /// <summary>
        /// 產品廠
        /// </summary>
        public string T0701 { get; set; }
        /// <summary>
        /// 成品大中類
        /// </summary>
        public string T0702 { get; set; }
        /// <summary>
        /// 失效日期
        /// </summary>
        public string T0703 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T0704 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T0705 { get; set; }
    }
}