// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T08
    {
        /// <summary>
        /// 產品廠代碼
        /// </summary>
        public string T0801 { get; set; }
        /// <summary>
        /// 部位序號
        /// </summary>
        public string T0802 { get; set; }
        /// <summary>
        /// 部位大類代碼
        /// </summary>
        public string T0803 { get; set; }
        /// <summary>
        /// 部位中類代碼
        /// </summary>
        public string T0804 { get; set; }
        /// <summary>
        /// 失效日期
        /// </summary>
        public string T0805 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T0806 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T0807 { get; set; }
    }
}