// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T14
    {
        /// <summary>
        /// 部件作法編碼
        /// </summary>
        public string T1401 { get; set; }
        /// <summary>
        /// 部件作法敘述
        /// </summary>
        public string T1402 { get; set; }
        /// <summary>
        /// 部件作法版次
        /// </summary>
        public string T1403 { get; set; }
        /// <summary>
        /// 部位大類代碼
        /// </summary>
        public string T1404 { get; set; }
        /// <summary>
        /// 部位中類代碼
        /// </summary>
        public string T1405 { get; set; }
        /// <summary>
        /// 單元工程編碼
        /// </summary>
        public string T1406 { get; set; }
        /// <summary>
        /// 單元工程版次
        /// </summary>
        public string T1407 { get; set; }
        /// <summary>
        /// 重要變更
        /// </summary>
        public string T1408 { get; set; }
        /// <summary>
        /// 效期(起)
        /// </summary>
        public string T1409 { get; set; }
        /// <summary>
        /// 效期(迄)
        /// </summary>
        public string T1410 { get; set; }
        /// <summary>
        /// 下架原因
        /// </summary>
        public string T1411 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T1412 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T1413 { get; set; }
        /// <summary>
        /// 已上傳圖片
        /// </summary>
        public string T1414 { get; set; }
        /// <summary>
        /// 已上傳影片
        /// </summary>
        public string T1415 { get; set; }
        /// <summary>
        /// 本作法是否開放
        /// </summary>
        public string T1416 { get; set; }
        /// <summary>
        /// 專銷品牌1
        /// </summary>
        public string T1417 { get; set; }
        /// <summary>
        /// 專銷品牌2
        /// </summary>
        public string T1418 { get; set; }
        /// <summary>
        /// 特放品牌1
        /// </summary>
        public string T1419 { get; set; }
        /// <summary>
        /// 特放品牌2
        /// </summary>
        public string T1420 { get; set; }
        /// <summary>
        /// 特放品牌3
        /// </summary>
        public string T1421 { get; set; }
        /// <summary>
        /// 特放品牌4
        /// </summary>
        public string T1422 { get; set; }
        /// <summary>
        /// 特放品牌5
        /// </summary>
        public string T1423 { get; set; }
        /// <summary>
        /// 特放品牌6
        /// </summary>
        public string T1424 { get; set; }
        /// <summary>
        /// 輔料代碼1
        /// </summary>
        public string T1425 { get; set; }
        /// <summary>
        /// 輔料簡稱1要維護詳盡規格
        /// </summary>
        public string T1426 { get; set; }
        /// <summary>
        /// 輔料備註1
        /// </summary>
        public string T1427 { get; set; }
        public string T1428 { get; set; }
        public string T1429 { get; set; }
        public string T1430 { get; set; }
        public string T1431 { get; set; }
        public string T1432 { get; set; }
        public string T1433 { get; set; }
        public string T1434 { get; set; }
        public string T1435 { get; set; }
        public string T1436 { get; set; }
        public string T1437 { get; set; }
        public string T1438 { get; set; }
        public string T1439 { get; set; }
        public string T1440 { get; set; }
        public string T1441 { get; set; }
        public string T1442 { get; set; }
        public string T1443 { get; set; }
        public string T1444 { get; set; }
        public string T1445 { get; set; }
        public string T1446 { get; set; }
        public string T1447 { get; set; }
        public string T1448 { get; set; }
        public string T1449 { get; set; }
        public string T1450 { get; set; }
        public string T1451 { get; set; }
        public string T1452 { get; set; }
        public string T1453 { get; set; }
        public string T1454 { get; set; }
        public string T1455 { get; set; }
        public string T1456 { get; set; }
        public string T1457 { get; set; }
        public string T1458 { get; set; }
        public string T1459 { get; set; }
        public string T1460 { get; set; }
        public string T1461 { get; set; }
        public string T1462 { get; set; }
        public string T1463 { get; set; }
        public string T1464 { get; set; }
        public string T1465 { get; set; }
        public string T1466 { get; set; }
        public string T1467 { get; set; }
        public string T1468 { get; set; }
        public string T1469 { get; set; }
        public string T1470 { get; set; }
        public string T1471 { get; set; }
        public string T1472 { get; set; }
        public string T1473 { get; set; }
        public string T1474 { get; set; }
        public string T1475 { get; set; }
        public string T1476 { get; set; }
        public string T1477 { get; set; }
        public string T1478 { get; set; }
        public string T1479 { get; set; }
        public string T1480 { get; set; }
        public string T1481 { get; set; }
        public string T1482 { get; set; }
        public string T1483 { get; set; }
        public string T1484 { get; set; }
        public string T1485 { get; set; }
        public string T1486 { get; set; }
        public string T1487 { get; set; }
        public string T1488 { get; set; }
        public string T1489 { get; set; }
        public string T1490 { get; set; }
        public string T1491 { get; set; }
        public string T1492 { get; set; }
        public string T1493 { get; set; }
        public string T1494 { get; set; }
        public string T1495 { get; set; }
        public string T1496 { get; set; }
        public string T1497 { get; set; }
        public string T1498 { get; set; }
        public string T1499 { get; set; }
        public string T1500 { get; set; }
        public string T1501 { get; set; }
        public string T1502 { get; set; }
        public string T1503 { get; set; }
        public string T1504 { get; set; }
        public string T1505 { get; set; }
        public string T1506 { get; set; }
        public string T1507 { get; set; }
        public string T1508 { get; set; }
        public string T1509 { get; set; }
        public string T1510 { get; set; }
        public string T1511 { get; set; }
        public string T1512 { get; set; }
        public string T1513 { get; set; }
        public string T1514 { get; set; }
        public string T1515 { get; set; }
        public string T1516 { get; set; }
        public string T1517 { get; set; }
        public string T1518 { get; set; }
        public string T1519 { get; set; }
        public string T1520 { get; set; }
        public string T1521 { get; set; }
        public string T1522 { get; set; }
        public string T1523 { get; set; }
        public string T1524 { get; set; }
        public string T1525 { get; set; }
        public string T1526 { get; set; }
        public string T1527 { get; set; }
        public string T1528 { get; set; }
        public string T1529 { get; set; }
        /// <summary>
        /// 部件作法備註
        /// </summary>
        public string T1530 { get; set; }
        /// <summary>
        /// 部件作法提示
        /// </summary>
        public string T1531 { get; set; }
    }
}