// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T15
    {
        /// <summary>
        /// 成品料號
        /// </summary>
        public string T1501 { get; set; }
        /// <summary>
        /// 成品顏色代碼
        /// </summary>
        public string T1502 { get; set; }
        /// <summary>
        /// 成品作法版次
        /// </summary>
        public string T1512 { get; set; }
        /// <summary>
        /// 部位大類代碼
        /// </summary>
        public string T1503 { get; set; }
        /// <summary>
        /// 部位中類代碼
        /// </summary>
        public string T1504 { get; set; }
        /// <summary>
        /// 成品作法項次
        /// </summary>
        public string T1505 { get; set; }
        /// <summary>
        /// 部件作法編碼
        /// </summary>
        public string T1506 { get; set; }
        /// <summary>
        /// 部件作法版次
        /// </summary>
        public string T1507 { get; set; }
        /// <summary>
        /// 成品作法備註
        /// </summary>
        public string T1508 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T1509 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T1510 { get; set; }
        /// <summary>
        /// 失效日期
        /// </summary>
        public string T1511 { get; set; }
        /// <summary>
        /// 產品廠
        /// </summary>
        public string T1513 { get; set; }
        /// <summary>
        /// 客戶簡稱
        /// </summary>
        public string T1514 { get; set; }
    }
}