// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T151
    {
        /// <summary>
        /// 成品料號
        /// </summary>
        public string T15101 { get; set; }
        /// <summary>
        /// 成品顏色代碼
        /// </summary>
        public string T15102 { get; set; }
        /// <summary>
        /// 成品作法版次
        /// </summary>
        public string T15259 { get; set; }
        /// <summary>
        /// 成品作法項次
        /// </summary>
        public string T15103 { get; set; }
        /// <summary>
        /// 部件作法編碼
        /// </summary>
        public string T15104 { get; set; }
        /// <summary>
        /// 部件作法版次
        /// </summary>
        public string T15105 { get; set; }
        /// <summary>
        /// 輔料項次
        /// </summary>
        public string T15106 { get; set; }
        /// <summary>
        /// 輔料代碼
        /// </summary>
        public string T15107 { get; set; }
        /// <summary>
        /// 輔料料號
        /// </summary>
        public string T15108 { get; set; }
        /// <summary>
        /// 輔料敘述
        /// </summary>
        public string T15109 { get; set; }
        /// <summary>
        /// 輔料顏色代碼
        /// </summary>
        public string T15110 { get; set; }
        /// <summary>
        /// 輔料顏色敘述
        /// </summary>
        public string T15111 { get; set; }
        /// <summary>
        /// 輔料備註
        /// </summary>
        public string T15112 { get; set; }
        /// <summary>
        /// 部件輔料單位
        /// </summary>
        public string T15113 { get; set; }
        /// <summary>
        /// 成品尺寸1
        /// </summary>
        public string T15114 { get; set; }
        /// <summary>
        /// 輔料長度/單件用量/裁切長度 1
        /// </summary>
        public decimal? T15115 { get; set; }
        /// <summary>
        /// 紙版備註1
        /// </summary>
        public string T15116 { get; set; }
        /// <summary>
        /// 輔料長度/裁切長度倍數 1
        /// </summary>
        public decimal? T15117 { get; set; }
        /// <summary>
        /// 成品尺寸2
        /// </summary>
        public string T15118 { get; set; }
        /// <summary>
        /// 輔料長度/單件用量/裁切長度 2
        /// </summary>
        public decimal? T15119 { get; set; }
        /// <summary>
        /// 紙版備註2
        /// </summary>
        public string T15120 { get; set; }
        /// <summary>
        /// 輔料長度/裁切長度倍數 2
        /// </summary>
        public decimal? T15121 { get; set; }
        public string T15122 { get; set; }
        public decimal? T15123 { get; set; }
        public string T15124 { get; set; }
        public decimal? T15125 { get; set; }
        public string T15126 { get; set; }
        public decimal? T15127 { get; set; }
        public string T15128 { get; set; }
        public decimal? T15129 { get; set; }
        public string T15130 { get; set; }
        public decimal? T15131 { get; set; }
        public string T15132 { get; set; }
        public decimal? T15133 { get; set; }
        public string T15134 { get; set; }
        public decimal? T15135 { get; set; }
        public string T15136 { get; set; }
        public decimal? T15137 { get; set; }
        public string T15138 { get; set; }
        public decimal? T15139 { get; set; }
        public string T15140 { get; set; }
        public decimal? T15141 { get; set; }
        public string T15142 { get; set; }
        public decimal? T15143 { get; set; }
        public string T15144 { get; set; }
        public decimal? T15145 { get; set; }
        public string T15146 { get; set; }
        public decimal? T15147 { get; set; }
        public string T15148 { get; set; }
        public decimal? T15149 { get; set; }
        public string T15150 { get; set; }
        public decimal? T15151 { get; set; }
        public string T15152 { get; set; }
        public decimal? T15153 { get; set; }
        public string T15154 { get; set; }
        public decimal? T15155 { get; set; }
        public string T15156 { get; set; }
        public decimal? T15157 { get; set; }
        public string T15158 { get; set; }
        public decimal? T15159 { get; set; }
        public string T15160 { get; set; }
        public decimal? T15161 { get; set; }
        public string T15162 { get; set; }
        public decimal? T15163 { get; set; }
        public string T15164 { get; set; }
        public decimal? T15165 { get; set; }
        public string T15166 { get; set; }
        public decimal? T15167 { get; set; }
        public string T15168 { get; set; }
        public decimal? T15169 { get; set; }
        public string T15170 { get; set; }
        public decimal? T15171 { get; set; }
        public string T15172 { get; set; }
        public decimal? T15173 { get; set; }
        /// <summary>
        /// 平切
        /// </summary>
        public string T15221 { get; set; }
        /// <summary>
        /// R角
        /// </summary>
        public string T15222 { get; set; }
        /// <summary>
        /// R角裁切模具編碼
        /// </summary>
        public string T15223 { get; set; }
        /// <summary>
        /// 其他裁切
        /// </summary>
        public string T15224 { get; set; }
        /// <summary>
        /// 其他裁切模具編碼
        /// </summary>
        public string T15225 { get; set; }
        /// <summary>
        /// 完整Logo
        /// </summary>
        public string T15226 { get; set; }
        /// <summary>
        /// 依紙版量測
        /// </summary>
        public string T15227 { get; set; }
        /// <summary>
        /// 斬如紙版
        /// </summary>
        public string T15228 { get; set; }
    }
}