// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T152
    {
        /// <summary>
        /// 成品料號
        /// </summary>
        public string T15201 { get; set; }
        /// <summary>
        /// 成品顏色代碼
        /// </summary>
        public string T15214 { get; set; }
        /// <summary>
        /// 成品尺寸
        /// </summary>
        public string T15215 { get; set; }
        /// <summary>
        /// 成品作法版次
        /// </summary>
        public string T15216 { get; set; }
        /// <summary>
        /// 部件作法編碼
        /// </summary>
        public string T15202 { get; set; }
        /// <summary>
        /// 輔料項次
        /// </summary>
        public string T15203 { get; set; }
        /// <summary>
        /// 輔料料號
        /// </summary>
        public string T15204 { get; set; }
        /// <summary>
        /// 輔料敘述
        /// </summary>
        public string T15205 { get; set; }
        /// <summary>
        /// 輔料顏色代碼
        /// </summary>
        public string T15206 { get; set; }
        /// <summary>
        /// 輔料顏色敘述
        /// </summary>
        public string T15207 { get; set; }
        /// <summary>
        /// 輔料清單單位
        /// </summary>
        public string T15208 { get; set; }
        /// <summary>
        /// 紙版備註
        /// </summary>
        public string T15209 { get; set; }
        /// <summary>
        /// 輔料長度(INCH)(含指定長度、裁切長度)
        /// </summary>
        public decimal? T15217 { get; set; }
        /// <summary>
        /// 輔料長度(CM)(含指定長度、裁切長度)
        /// </summary>
        public decimal? T15218 { get; set; }
        /// <summary>
        /// 輔料基礎單位(Base Unit of Measure)
        /// </summary>
        public string T15220 { get; set; }
        /// <summary>
        /// 輔料倍數
        /// </summary>
        public decimal? T15210 { get; set; }
        /// <summary>
        /// 物料需求量(BOM requirement)(YD/M)
        /// </summary>
        public decimal? T15211 { get; set; }
        /// <summary>
        /// 損耗係數 (YD/M)
        /// </summary>
        public decimal? T15212 { get; set; }
        /// <summary>
        /// 損耗加量
        /// </summary>
        public decimal? T15219 { get; set; }
        /// <summary>
        /// 標準物料需求量(Standard BOM requirement) (YD/M)
        /// </summary>
        public decimal? T15213 { get; set; }
        /// <summary>
        /// 平切
        /// </summary>
        public string T15221 { get; set; }
        /// <summary>
        /// R角
        /// </summary>
        public string T15222 { get; set; }
        /// <summary>
        /// R角裁切模具編碼
        /// </summary>
        public string T15223 { get; set; }
        /// <summary>
        /// 其他裁切
        /// </summary>
        public string T15224 { get; set; }
        /// <summary>
        /// 其他裁切模具編碼
        /// </summary>
        public string T15225 { get; set; }
        /// <summary>
        /// 完整Logo
        /// </summary>
        public string T15226 { get; set; }
        /// <summary>
        /// 依紙版量測
        /// </summary>
        public string T15227 { get; set; }
        /// <summary>
        /// 斬如紙版
        /// </summary>
        public string T15228 { get; set; }
    }
}