// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T17
    {
        /// <summary>
        /// 合約號碼
        /// </summary>
        public string T1701 { get; set; }
        /// <summary>
        /// 合約項次
        /// </summary>
        public string T1702 { get; set; }
        /// <summary>
        /// 成品料號
        /// </summary>
        public string T1703 { get; set; }
        /// <summary>
        /// 成品顏色代碼
        /// </summary>
        public string T1704 { get; set; }
        /// <summary>
        /// 工廠
        /// </summary>
        public string T1705 { get; set; }
        /// <summary>
        /// 部位大類代碼
        /// </summary>
        public string T1706 { get; set; }
        /// <summary>
        /// 部位中類代碼
        /// </summary>
        public string T1707 { get; set; }
        /// <summary>
        /// 成品作法項次
        /// </summary>
        public string T1708 { get; set; }
        /// <summary>
        /// 部件作法編碼
        /// </summary>
        public string T1709 { get; set; }
        /// <summary>
        /// 部件作法版次
        /// </summary>
        public string T1710 { get; set; }
        /// <summary>
        /// 作法備註
        /// </summary>
        public string T1711 { get; set; }
        /// <summary>
        /// 資料更新人員
        /// </summary>
        public string T1712 { get; set; }
        /// <summary>
        /// 資料更新日期
        /// </summary>
        public DateTime T1713 { get; set; }
        /// <summary>
        /// 刪除註記
        /// </summary>
        public string T1714 { get; set; }
        /// <summary>
        /// 成品作法版次
        /// </summary>
        public string T1715 { get; set; }
    }
}