// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T171
    {
        /// <summary>
        /// 合約號碼
        /// </summary>
        public string T17101 { get; set; }
        /// <summary>
        /// 合約項次
        /// </summary>
        public string T17102 { get; set; }
        /// <summary>
        /// 成品料號
        /// </summary>
        public string T17103 { get; set; }
        /// <summary>
        /// 成品顏色代碼
        /// </summary>
        public string T17104 { get; set; }
        /// <summary>
        /// 工廠
        /// </summary>
        public string T17105 { get; set; }
        /// <summary>
        /// 部件作法項次
        /// </summary>
        public string T17106 { get; set; }
        /// <summary>
        /// 部件作法編碼
        /// </summary>
        public string T17107 { get; set; }
        /// <summary>
        /// 部件作法版次
        /// </summary>
        public string T17108 { get; set; }
        /// <summary>
        /// 輔料項次
        /// </summary>
        public string T17109 { get; set; }
        /// <summary>
        /// 輔料簡稱
        /// </summary>
        public string T17110 { get; set; }
        /// <summary>
        /// 輔料料號
        /// </summary>
        public string T17111 { get; set; }
        /// <summary>
        /// 輔料敘述
        /// </summary>
        public string T17112 { get; set; }
        /// <summary>
        /// 輔料顏色代碼
        /// </summary>
        public string T17113 { get; set; }
        /// <summary>
        /// 輔料顏色敘述
        /// </summary>
        public string T17114 { get; set; }
        /// <summary>
        /// 輔料備註
        /// </summary>
        public string T17115 { get; set; }
        /// <summary>
        /// 輔料單位
        /// </summary>
        public string T17116 { get; set; }
        /// <summary>
        /// 成品尺寸1
        /// </summary>
        public string T17117 { get; set; }
        /// <summary>
        /// 輔料長度1
        /// </summary>
        public decimal? T17118 { get; set; }
        /// <summary>
        /// 輔料倍數1
        /// </summary>
        public decimal? T17119 { get; set; }
        /// <summary>
        /// 成品尺寸2
        /// </summary>
        public string T17120 { get; set; }
        /// <summary>
        /// 輔料長度2
        /// </summary>
        public decimal? T17121 { get; set; }
        /// <summary>
        /// 輔料倍數2
        /// </summary>
        public decimal? T17122 { get; set; }
        /// <summary>
        /// 成品尺寸3
        /// </summary>
        public string T17123 { get; set; }
        /// <summary>
        /// 輔料長度3
        /// </summary>
        public decimal? T17124 { get; set; }
        /// <summary>
        /// 輔料倍數3
        /// </summary>
        public decimal? T17125 { get; set; }
        /// <summary>
        /// 成品尺寸4
        /// </summary>
        public string T17126 { get; set; }
        /// <summary>
        /// 輔料長度4
        /// </summary>
        public decimal? T17127 { get; set; }
        /// <summary>
        /// 輔料倍數4
        /// </summary>
        public decimal? T17128 { get; set; }
        /// <summary>
        /// 成品尺寸5
        /// </summary>
        public string T17129 { get; set; }
        /// <summary>
        /// 輔料長度5
        /// </summary>
        public decimal? T17130 { get; set; }
        /// <summary>
        /// 輔料倍數5
        /// </summary>
        public decimal? T17131 { get; set; }
        /// <summary>
        /// 成品尺寸6
        /// </summary>
        public string T17132 { get; set; }
        /// <summary>
        /// 輔料長度6
        /// </summary>
        public decimal? T17133 { get; set; }
        /// <summary>
        /// 輔料倍數6
        /// </summary>
        public decimal? T17134 { get; set; }
        /// <summary>
        /// 成品尺寸7
        /// </summary>
        public string T17135 { get; set; }
        /// <summary>
        /// 輔料長度7
        /// </summary>
        public decimal? T17136 { get; set; }
        /// <summary>
        /// 輔料倍數7
        /// </summary>
        public decimal? T17137 { get; set; }
        /// <summary>
        /// 成品尺寸8
        /// </summary>
        public string T17138 { get; set; }
        /// <summary>
        /// 輔料長度8
        /// </summary>
        public decimal? T17139 { get; set; }
        /// <summary>
        /// 輔料倍數8
        /// </summary>
        public decimal? T17140 { get; set; }
        /// <summary>
        /// 成品尺寸9
        /// </summary>
        public string T17141 { get; set; }
        /// <summary>
        /// 輔料長度9
        /// </summary>
        public decimal? T17142 { get; set; }
        /// <summary>
        /// 輔料倍數9
        /// </summary>
        public decimal? T17143 { get; set; }
        /// <summary>
        /// 成品尺寸10
        /// </summary>
        public string T17144 { get; set; }
        /// <summary>
        /// 輔料長度10
        /// </summary>
        public decimal? T17145 { get; set; }
        /// <summary>
        /// 輔料倍數10
        /// </summary>
        public decimal? T17146 { get; set; }
        /// <summary>
        /// 成品尺寸11
        /// </summary>
        public string T17147 { get; set; }
        /// <summary>
        /// 輔料長度11
        /// </summary>
        public decimal? T17148 { get; set; }
        /// <summary>
        /// 輔料倍數11
        /// </summary>
        public decimal? T17149 { get; set; }
        /// <summary>
        /// 成品尺寸12
        /// </summary>
        public string T17150 { get; set; }
        /// <summary>
        /// 輔料長度12
        /// </summary>
        public decimal? T17151 { get; set; }
        /// <summary>
        /// 輔料倍數12
        /// </summary>
        public decimal? T17152 { get; set; }
        /// <summary>
        /// 成品尺寸13
        /// </summary>
        public string T17153 { get; set; }
        /// <summary>
        /// 輔料長度13
        /// </summary>
        public decimal? T17154 { get; set; }
        /// <summary>
        /// 輔料倍數13
        /// </summary>
        public decimal? T17155 { get; set; }
        /// <summary>
        /// 成品尺寸14
        /// </summary>
        public string T17156 { get; set; }
        /// <summary>
        /// 輔料長度14
        /// </summary>
        public decimal? T17157 { get; set; }
        /// <summary>
        /// 輔料倍數14
        /// </summary>
        public decimal? T17158 { get; set; }
        /// <summary>
        /// 成品尺寸15
        /// </summary>
        public string T17159 { get; set; }
        /// <summary>
        /// 輔料長度15
        /// </summary>
        public decimal? T17160 { get; set; }
        /// <summary>
        /// 輔料倍數15
        /// </summary>
        public decimal? T17161 { get; set; }
    }
}