// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T91
    {
        /// <summary>
        /// 物料料號
        /// </summary>
        public string T9101 { get; set; }
        /// <summary>
        /// 物料敘述
        /// </summary>
        public string T9102 { get; set; }
        /// <summary>
        /// CATEGORY
        /// </summary>
        public string T9103 { get; set; }
        /// <summary>
        /// AS-400版號(Parent code)
        /// </summary>
        public string T9104 { get; set; }
        /// <summary>
        /// MQ
        /// </summary>
        public string T9105 { get; set; }
        /// <summary>
        /// MODEL
        /// </summary>
        public string T9106 { get; set; }
        /// <summary>
        /// CLOSURE STYLE
        /// </summary>
        public string T9107 { get; set; }
        /// <summary>
        /// 認證類別
        /// </summary>
        public string T9108 { get; set; }
        /// <summary>
        /// 款式說明
        /// </summary>
        public string T9109 { get; set; }
        /// <summary>
        /// 尺寸範圍
        /// </summary>
        public string T9110 { get; set; }
        /// <summary>
        /// 單位(Base Unit of Measure)
        /// </summary>
        public string T9111 { get; set; }
        /// <summary>
        /// 物料狀態
        /// </summary>
        public string T9112 { get; set; }
    }
}