// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T92
    {
        /// <summary>
        /// 物料料號
        /// </summary>
        public string T9201 { get; set; }
        /// <summary>
        /// 顏色代碼
        /// </summary>
        public string T9202 { get; set; }
        /// <summary>
        /// 尺寸代碼
        /// </summary>
        public string T9203 { get; set; }
        /// <summary>
        /// 地區代碼
        /// </summary>
        public string T9204 { get; set; }
        /// <summary>
        /// 顏色敘述
        /// </summary>
        public string T9205 { get; set; }
        /// <summary>
        /// 成品grid
        /// </summary>
        public string T9206 { get; set; }
        /// <summary>
        /// 物料狀態
        /// </summary>
        public string T9207 { get; set; }
    }
}