// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T93
    {
        /// <summary>
        /// 成品料號
        /// </summary>
        public string T9301 { get; set; }
        /// <summary>
        /// 成品尺寸
        /// </summary>
        public string T9302 { get; set; }
    }
}