// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T94
    {
        /// <summary>
        /// 合約號碼
        /// </summary>
        public string T9401 { get; set; }
        /// <summary>
        /// 合約項次
        /// </summary>
        public string T9402 { get; set; }
        /// <summary>
        /// 成品料號
        /// </summary>
        public string T9403 { get; set; }
        /// <summary>
        /// 成品顏色代碼
        /// </summary>
        public string T9404 { get; set; }
        /// <summary>
        /// 交貨日期
        /// </summary>
        public string T9405 { get; set; }
        /// <summary>
        /// CUST ITEM
        /// </summary>
        public string T9406 { get; set; }
        /// <summary>
        /// 製單人員
        /// </summary>
        public string T9407 { get; set; }
        /// <summary>
        /// 業務人員
        /// </summary>
        public string T9408 { get; set; }
    }
}