// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Clothes.Dal.Models
{
    public partial class T95
    {
        /// <summary>
        /// 工單號碼WO No.
        /// </summary>
        public string T9501 { get; set; }
        /// <summary>
        /// 工廠Plant
        /// </summary>
        public string T9502 { get; set; }
        /// <summary>
        /// 成品料號
        /// </summary>
        public string T9503 { get; set; }
        /// <summary>
        /// 成品顏色
        /// </summary>
        public string T9504 { get; set; }
        /// <summary>
        /// 成品尺寸
        /// </summary>
        public string T9505 { get; set; }
        /// <summary>
        /// 成品地區
        /// </summary>
        public string T9506 { get; set; }
        /// <summary>
        /// Target Qty
        /// </summary>
        public decimal T9507 { get; set; }
        /// <summary>
        /// UL lot nub
        /// </summary>
        public string T9508 { get; set; }
        /// <summary>
        /// Issue Date
        /// </summary>
        public string T9509 { get; set; }
        /// <summary>
        /// WO Q&apos;ty
        /// </summary>
        public decimal T9510 { get; set; }
    }
}